### ISSUE TITLE
nai相关参数问题

### ISSUE THREAD

**Issue by dtlnor** [sudoskys/StableDiffusionBook#17]
https://stable-diffusion-book.vercel.app/4_model/#nai_1
https://stable-diffusion-book.vercel.app/5_drawing/#nai
这两段的内容同质而冲突了，特别是5_drawing/#nai，内容有重复（比如noise seed部分）而且与紧接着的下段内容冲突（下段内容描述需要设置strength跟noise，但上面又说设置noise seed不需要设置strength与noise，没有说明根据官方代码31337等价 0.69 / 0.67）

**Comment by sudoskys** [comment]
是的，原来统属是模型调试的内容，后来重构并添加之后有重复内容

**Comment by sudoskys** [comment]
上面是 翻译内容，原文说在webui只需要默认值不需要使用NAI的参数内容。
会调整一下顺序

**Comment by sudoskys** [comment]
此问题在 https://github.com/sudoskys/StableDiffusionBook/commit/88a7bab97bcd3f4a02b1d662162aa89cb6286a37 中得到改善
