### ISSUE TITLE
更合适的缩写

### ISSUE THREAD

**Issue by dtlnor** [sudoskys/StableDiffusionBook#2]
一般来说，在命名简写、缩写的时候都会有一定的规则、规律。或者直接采用已有的缩写。
stable diffusion这种两个词的简写可以很简单地缩写为SD或者S.D.，但stable diffusion webUI缩写成SD丢失太多信息了（我不清楚是不是笔误，因为我在看后文的时候是写“SD网页应用”这样的用法，明显跟首页“术语”栏目不同，而且“魔杖”也不知道在说什么…），而且也跟SD模型/算法本身冲突了。如果要省略信息的简写，webUI可能更恰当（也更符合大部分人现有的使用习惯）或者保留完整信息就是SDWebUI
而NV这种简写方式也很奇怪，nv两个字取自novel的两个元音，却省略了后面的AI，词意就不完整。一般来说如果是两个词的缩写，起码会保留字首（比如英文社区现在的缩写就是NAI（AI本身是缩写）），如果保留元音也应该是NVAI。如果按照现有的社区习惯，NAI是更恰当的缩写命名

**Comment by lychees** [comment]
其实基本没歧义，而且海外社区也同样用这种缩写。

**Comment by sudoskys** [comment]
好的，下次修改会统一一下，目前vercel改动次数冷却中

**Comment by sudoskys** [comment]
https://github.com/sudoskys/StableDiffusionBook/commit/313d9dd065985d5de76573f9f8f0bf9206ce4ca4
