### ISSUE TITLE
关于绘画调试中"训练"章节可能存在的错误

### ISSUE THREAD

**Issue by uf-hy** [sudoskys/StableDiffusionBook#21]
在[绘画调试中的"训练"](https://github.com/sudoskys/StableDiffusionBook/blob/main/docs/5_drawing.md#%E8%AE%AD%E7%BB%83)中, 提到了`Learning rate(学习率)，决定训练的速度。Learning rate越低学习越慢（花费更长的时间收敛）。`
但是在下一行又提到了, `一般为 0.005。，如果想快一些，可以使用 0.001 加快`  
明显的, 如果前文是正确的, 如果想快一些, Learning rate应该需要更大, 而0.001明显低于0.005.  
我猜想是否如同在同一行的句号(`。`)后多打了一个`，`一样, 在`0.001`处多打了一个0,
亦或者是我理解错语境了, 如若如此还请提醒

**Comment by sudoskys** [comment]
好的

**Comment by sudoskys** [comment]
已修正
