### ISSUE TITLE
[建议]加个除了vercel之外的部署站

### ISSUE THREAD

**Issue by PureSnowFox** [sudoskys/StableDiffusionBook#23]
国内目前是墙了vercel的，可以考虑加多其他的部署站，比如netlify.app

我自己目前整了个分流的：https://stablediffusionbook.netlify.app/ ，如果有需求删掉的话回复我(

**Comment by sudoskys** [comment]
我会在首页添加信息，注明您的分流

**Comment by sudoskys** [comment]
已经添加
