### ISSUE TITLE
第一次审计

### ISSUE THREAD

**Issue by sudoskys** [sudoskys/StableDiffusionBook#33]
- [x] 审计 页1
https://github.com/sudoskys/StableDiffusionBook/issues/40
- [x] 审计 页2
#34 @lostDeers 
- [x] 审计 页3
https://github.com/sudoskys/StableDiffusionBook/issues/40
- [x] 审计 页4
#37 @sakurayang 
- [x] 审计 页6
#35 @CCRcmcpe 
- [x] 审计 页7

- [x] 第一次审计：查找内容错误

- [x] 第一次审计：查找逻辑错误，语法病句，结构混乱，内容过时，上下冲突，错词怪词

- [x] 修改文档页6，解释术语和修复格式

**备份任务**

因为WebDev的特殊性，每三天自动 Clone

**Comment by sudoskys** [comment]
咕咕咕

**Comment by sudoskys** [comment]
语法错误注意，翻译腔修正，重写关键内容，分步指南

**Comment by wfjsw** [comment]
在 https://github.com/wfjsw/VP-StableDiffusionBook 开了个副本整理了一下结构

~~因为改的文件太多了 diff 不出改了什么来~~

md 文件里有一些 TODO 注释是我看了一眼感觉有问题的部分，第二遍再过这些

**Comment by sudoskys** [comment]
> 在 https://github.com/wfjsw/VP-StableDiffusionBook 开了个副本整理了一下结构
> 
> ~因为改的文件太多了 diff 不出改了什么来~
> 
> md 文件里有一些 TODO 注释是我看了一眼感觉有问题的部分，第二遍再过这些

天，我现在才看到，我几天前重构了一下，现在添加了一些新的内容，可以同步一下。
