### ISSUE TITLE
Can't unpickled ckpt

### ISSUE THREAD

**Issue by Linaqruf** [sudoskys/StableDiffusionBook#56]
Hi, how to fix this issue? I use your safeunpickle.py to unpickle pickled ckpt, but it's always failed.

![image](https://user-images.githubusercontent.com/50163983/200622493-1e58eeaa-c47e-41cd-a71e-8f393eab384f.png)

**Comment by sudoskys** [comment]
[Related](https://www.reddit.com/r/sdforall/comments/y5axt7/with_lots_of_models_appearing_due_merging_and/)

[Another](https://github.com/lopho/pickle_inspector)

**Comment by Linaqruf** [comment]
Thanks for answering. 
I'll check the link.
