### ISSUE TITLE
[ADD] 推荐友链，元素同典

### ISSUE THREAD

**Issue by 1847905557** [sudoskys/StableDiffusionBook#60]
元素同典：确实不完全科学的魔导书
https://docs.qq.com/doc/DWFdSTHJtQWRzYk9k

一本元素法典社区制作的入门教程，11月12号完成了第二次修订，用尽可能通俗的语言介绍了一些基本概念、常见问题并展示了对应解决方案与思路引导

**Comment by sudoskys** [comment]
友链？(挠头)
您是文档维护者吗？

**Comment by sudoskys** [comment]
https://github.com/sudoskys/StableDiffusionBook/commit/00937f5dcc66a7aa2e2780b0043dffb9def57790
已经添加入 Readme

**Comment by sudoskys** [comment]
另外！欢迎参加 Wiki 协作和审查语法错误和技术性错误 [贡献指南](https://draw.dianas.cyou/GettingStarted/contributing/)

**Comment by 1847905557** [comment]
> 友链？(挠头) 您是文档维护者吗？ 第一次听说文档有友链，应该是 添加外链 ？

是的，主编(文中的技术审校+支持)是我，其实是那个意思，但是脑抽了一时想不起来它叫什么了
