### ISSUE TITLE
整体内容/目录重新整理需求

### ISSUE THREAD

**Issue by SteelPlate45** [sudoskys/StableDiffusionBook#87]
考不考虑重构一下，变成
前言/准备 - 软件安装 - 基础应用（原版功能解释） - 进阶应用（各种插件） - 应用实例 - SD理论（用于引用和扩展解释）
的结构？

**Comment by sudoskys** [comment]
目前的目录好像就是这个结构呀

**Comment by sudoskys** [comment]
起步于此，开始之前，  -- 先行介绍
安装配置，调试程序 --安装程序
绘画指南 -- 应用实例
训练模型  -- 应用
参考资料  -- 扩展

**Comment by SteelPlate45** [comment]
了解了，可能是因为子级分类不够清晰导致我理解出现了偏差，我会再通读一遍后再写一份提纲 - 此外，考不考虑顶部目录做一个悬停？不然一直要滚到顶端切换还是挺麻烦的

**Comment by sudoskys** [comment]
可以考虑一下。（其实有一个回到顶端按钮）

**Comment by SteelPlate45** [comment]
> 可以考虑一下。（其实有一个回到顶端按钮）

（但感觉还是不算很方便，如果目录悬停且侧面可以自动切换章节应该会好很多
